---
name: "Acceptance Test"
on:
  push:
    branches:
      - "dev/amauat-ipc-issue-latest-firefox"
jobs:
  test:
    name: "Test ${{ matrix.tag }} on ${{ matrix.browser }}"
    runs-on: "ubuntu-18.04"
    continue-on-error: true
    strategy:
      matrix:
        tag:
          - "aip-encrypt"
          - "aip-encrypt-mirror"
          - "black-box"
          - "icc"
          - "'ipc --tags=access'"
          - "'ipc --tags=preservation'"
          - "mo-aip-reingest"
          - "tcc"
          - "tpc"
          - "uuids-dirs"
        browser:
          - "Firefox"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v2"
        with:
          submodules: true
      - name: "Create external volumes"
        run: |
          make -C hack/ create-volumes
      - name: "Start MySQL"
        run: |
          docker-compose up -d mysql
        working-directory: ./hack
      - name: "Build images"
        run: |
          make -C hack/ build
      - name: "Start services"
        run: |
          docker-compose up -d
        env:
          cluster.routing.allocation.disk.threshold_enabled: false
        working-directory: ./hack
      - name: "Bootstrap services"
        run: |
          make -C hack/ bootstrap
      - name: "Restart services"
        run: |
          make -C hack/ restart-am-services
      - name: "Run AMAUAT tag"
        run: |
          make -C hack/ test-at-behave TAGS=${{ matrix.tag }} BROWSER=${{ matrix.browser }}
